// app/layout.js
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  import RootLayout from "./RootLayout";
  
  export default function Layout({ children }) {
    return <RootLayout>{children}</RootLayout>;
  }